name: Update theme

# curl -H "Accept: application/vnd.github.v3+json" \
#    -H "Authorization: token ..." \
#    --request POST \
#    --data '{"event_type": "fetch_latest_changes" }' \
#    https://api.github.com/repos/adobe/aem-site-template-basic-theme-e2e/dispatches

on:
  schedule:
    - cron:  '0 1 * * *'
  repository_dispatch:
    types: fetch_latest_changes

jobs:

  update:
    name: Update theme based on AEM Site Template Basic repo
    runs-on: ubuntu-latest

    steps:
      - id: site_template
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: adobe/aem-site-template-basic
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise GITHUB_TOKEN is used, instead of TOKEN_WITH_WORKFLOW_WRITE_PERMISSIONS
      
      - name: Compute env vars
        id: env_vars
        run: |
          VERSION=$(echo ${{ steps.site_template.outputs.release }} | cut -f2 -d"v")
          echo ::set-output name=ZIP_PATH::$(echo "https://github.com/adobe/aem-site-template-basic/releases/download/${{ steps.site_template.outputs.release }}/aem-site-template-basic-$VERSION.zip")
          echo ::set-output name=TAG_NAME::$(echo "site-theme-from-site-template-${{ steps.site_template.outputs.release }}")

      - name: Site Template – download and unzip
        run: |
          curl --location --output site-template-tmp/site-template.zip --create-dirs ${{ steps.env_vars.outputs.ZIP_PATH }}
          unzip site-template-tmp/site-template.zip -d site-template-tmp

      - name: Site Theme – unzip, copy into root, change background and then cleanup
        run: |
          unzip site-template-tmp/theme-sources.zip -d site-template-tmp/site-theme-sources
          cp -frT site-template-tmp/site-theme-sources ./
          ls -la
          rm -fr site-template-tmp

      - name: Commit site theme and create tag
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "Release action on behalf of ${{ github.actor }}"
          git add --all
          git commit -am 'Commit ${{ steps.env_vars.outputs.TAG_NAME }}'
          git tag ${{ steps.env_vars.outputs.TAG_NAME }} -m "${{ steps.env_vars.outputs.TAG_NAME }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_WITH_WORKFLOW_WRITE_PERMISSIONS }}
          branch: ${{ github.ref }}
          force: true # simple use "theirs" merge-conflict strategy
          tags: true

      - name: Site Theme – pause for 3 sec, change background color and add version to README
        run: |
          sleep 3
          sed -i 's/#FFFFFF/pink/g' src/site/_variables.scss
          printf "\nVersion: %s" "$(date)" >> README.md

      - name: Commit site theme
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "Release action on behalf of ${{ github.actor }}"
          git add --all
          git commit -am 'Pink'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_WITH_WORKFLOW_WRITE_PERMISSIONS }}
          branch: ${{ github.ref }}
          force: true # simple use "theirs" merge-conflict strategy
          tags: true
