# This is a basic workflow to help you deploy theme changes

name: Build and deploy to Github artifacts

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Build artifacts for production
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: site-theme
          path: ${{ github.workspace }}/dist/**/*
